### ISSUE TITLE
Getting permission denied in docker run

### ISSUE THREAD

**Issue by mstfmomin** [samik-saha/rasa-chatbot#1]
First all, thanks for making such a great repo for rasa chatbot ready to deploy in heroku.  I m follwing your instructions, however, when I run, 

`docker run -it --rm -p 5005:5005 -e PORT=5005 rasa-chatbot`

It says permission denied. What should I do?

**Comment by samik-saha** [comment]
Thanks, @mstfmomin for reporting the issue. It seems the code is not working for the latest version of rasa packages. For now, I have updated the Dockerfile to install the specific versions for which it works. Please try it now. In the meantime, I will try to update the code to work with the latest rasa version.
